### ISSUE TITLE
how Building the firmware with the OpenSTM32 IDE (IAR)

### ISSUE THREAD

**Issue by huixiesui** [St3dPrinter/Marlin4ST#2]
How to import the IAR version?

"The firmware comes with the complete source code for the OpenSTM32 (free) and IAR
development environments."

I use OpenSTM32  import the Marlin4ST project errors.

**Comment by St3dPrinter** [comment]
@huixiesui , can you send the console log?
Did you correctly set the workspace path ? It should be stm32_cube, because all path in the project are relative path to stm32_cube.

**Comment by huixiesui** [comment]
Thank you for your reply。

After import errors, I'm going to try to change the operating system test.（I think may be the result of AC6 IDE error.）

The following report will be sent to Eclipse:

------
STATUS
------
pluginId            org.eclipse.cdt.core
pluginVersion       5.11.0.201602051005
code                0
severity            4
message             Error: required build system is not installed
fingerprint         821e369e579e156f14adb0979793c9a6

Exception:org.eclipse.core.runtime.CoreException: required build system is not installed
	 at org.eclipse.cdt.internal.core.settings.model.ExceptionFactory.createCoreException(ExceptionFactory.java:22)
	 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProvider(CProjectDescriptionManager.java:1190)
	 at org.eclipse.cdt.internal.core.settings.model.CConfigurationDescriptionCache.loadData(CConfigurationDescriptionCache.java:135)
	 at org.eclipse.cdt.internal.core.settings.model.CProjectDescription.loadDatas(CProjectDescription.java:196)
	 at org.eclipse.cdt.internal.core.settings.model.xml.XmlProjectDescriptionStorage.loadProjectDescription(XmlProjectDescriptionStorage.java:500)
	 at org.eclipse.cdt.internal.core.settings.model.xml.XmlProjectDescriptionStorage.getProjectDescription(XmlProjectDescriptionStorage.java:237)
	 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescriptionInternal(CProjectDescriptionManager.java:437)
	 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescription(CProjectDescriptionManager.java:419)
	 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescription(CProjectDescriptionManager.java:413)
	 at org.eclipse.cdt.internal.core.settings.model.CProjectDescriptionManager.getProjectDescription(CProjectDescriptionManager.java:406)
	 at org.eclipse.cdt.internal.core.model.CProject.computeSourceRoots(CProject.java:584)
	 at org.eclipse.cdt.internal.core.model.CProject.computeChildren(CProject.java:605)
	 at org.eclipse.cdt.internal.core.model.CProject.buildStructure(CProject.java:569)
	 at org.eclipse.cdt.internal.core.model.Openable.generateInfos(Openable.java:261)
	 at org.eclipse.cdt.internal.core.model.CElement.openWhenClosed(CElement.java:427)
	 at org.eclipse.cdt.internal.core.model.CElement.getElementInfo(CElement.java:305)
	 at org.eclipse.cdt.internal.core.model.CElement.getElementInfo(CElement.java:295)
	 at org.eclipse.cdt.internal.core.model.Parent.getChildren(Parent.java:55)
	 at org.eclipse.cdt.internal.core.model.CProject.getSourceRoots(CProject.java:467)
	 at org.eclipse.cdt.internal.core.model.CModelManager.create(CModelManager.java:337)
	 at org.eclipse.cdt.internal.core.model.CModelManager.create(CModelManager.java:265)
	 at org.eclipse.cdt.internal.core.model.DeltaProcessor.createElement(DeltaProcessor.java:87)
	 at org.eclipse.cdt.internal.core.model.DeltaProcessor.traverseDelta(DeltaProcessor.java:453)
	 at org.eclipse.cdt.internal.core.model.DeltaProcessor.traverseDelta(DeltaProcessor.java:471)
	 at org.eclipse.cdt.internal.core.model.DeltaProcessor.processResourceDelta(DeltaProcessor.java:433)
	 at org.eclipse.cdt.internal.core.model.CModelManager.resourceChanged(CModelManager.java:900)
	 at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	 at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	 at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:373)
	 at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1470)
	 at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:46)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

------
STATUS
------
pluginId            org.eclipse.cdt.core
pluginVersion       5.11.0.201602051005
code                0
severity            4
message             required build system is not installed [detached from CoreException of Status 'Error: required build system is not installed' by Error Reporting]
fingerprint         04927bcdd8468e15312afc06d92ade68


------
REPORT
------
anonymousId         cf97e692-be11-40b0-ba43-640129c8f684
name                
email               
comment             
eclipseBuildId      4.5.2.M20160212-1500
eclipseProduct      org.eclipse.epp.package.cpp.product
javaRuntimeVersion  1.8.0_101-b13
osgiWs              win32
osgiOs              Windows10
osgiOsVersion       10.0.0
osgiArch            x86_64
severity            UNKNOWN

-------
BUNDLES
-------
name                org.eclipse.cdt.core
version             5.11.0.201602051005

name                org.eclipse.cdt
version             8.8.1.201602051005

name                org.eclipse.core.jobs
version             3.7.0.v20150330-2103

name                org.eclipse.core.resources
version             3.10.1.v20150725-1910

name                org.eclipse.core.runtime
version             3.11.1.v20150903-1804





The following report will be sent to Eclipse:

------
STATUS
------
pluginId            org.eclipse.epp.logging.aeri.ide
pluginVersion       1.100.0.v20160217-0435
code                6
severity            4
message             Saving preferences failed: reporterName=null ; version: 1.100.0.v20160217-0435
fingerprint         5414c9508631816f84eba7055aad2d0a

Exception:java.lang.NullPointerException: null
	 at org.eclipse.core.internal.preferences.EclipsePreferences.put(EclipsePreferences.java:908)
	 at org.eclipse.ui.preferences.ScopedPreferenceStore.putValue(ScopedPreferenceStore.java:486)
	 at org.eclipse.epp.internal.logging.aeri.ide.di.SystemSettingsCreationFunction$1.notifyChanged(SystemSettingsCreationFunction.java:97)
	 at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	 at org.eclipse.epp.logging.aeri.core.impl.UserSettingsImpl.setReporterName(UserSettingsImpl.java:196)
	 at org.eclipse.epp.logging.aeri.core.impl.UserSettingsImpl.eSet(UserSettingsImpl.java:296)
	 at org.eclipse.epp.logging.aeri.core.impl.SystemSettingsImpl.eSet(SystemSettingsImpl.java:356)
	 at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1071)
	 at org.eclipse.epp.internal.logging.aeri.ide.utils.Servers.copyIfUnset(Servers.java:152)
	 at org.eclipse.epp.internal.logging.aeri.ide.utils.Servers.setAsDefaults(Servers.java:124)
	 at org.eclipse.epp.internal.logging.aeri.ide.dialogs.EclipseServerPage.dispose(EclipseServerPage.java:195)
	 at org.eclipse.jface.wizard.Wizard.dispose(Wizard.java:197)
	 at org.eclipse.jface.wizard.WizardDialog.hardClose(WizardDialog.java:846)
	 at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:807)
	 at org.eclipse.epp.internal.logging.aeri.ide.handlers.OpenSystemSetupWizardHandler$1.finishPressed(OpenSystemSetupWizardHandler.java:65)
	 at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
	 at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	 at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	 at org.eclipse.jface.window.Window.open(Window.java:803)
	 at org.eclipse.epp.internal.logging.aeri.ide.handlers.OpenSystemSetupWizardHandler.execute(OpenSystemSetupWizardHandler.java:69)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
	 at java.lang.reflect.Method.invoke(null:-1)
	 at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	 at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	 at org.eclipse.epp.logging.aeri.core.SystemControl.executeHandler(SystemControl.java:109)
	 at org.eclipse.epp.internal.logging.aeri.ide.notifications.SetupSystemNotification$1.execute(SetupSystemNotification.java:44)
	 at org.eclipse.epp.internal.logging.aeri.ide.notifications.NotificationPopup$1.linkActivated(NotificationPopup.java:264)
	 at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:233)
	 at org.eclipse.ui.forms.widgets.ImageHyperlink.handleActivate(ImageHyperlink.java:201)
	 at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:327)
	 at org.eclipse.ui.forms.widgets.AbstractHyperlink.access$2(AbstractHyperlink.java:311)
	 at org.eclipse.ui.forms.widgets.AbstractHyperlink$4.handleEvent(AbstractHyperlink.java:125)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
	 at java.lang.reflect.Method.invoke(null:-1)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

------
REPORT
------
anonymousId         cf97e692-be11-40b0-ba43-640129c8f684
name                
email               
comment             
eclipseBuildId      4.5.2.M20160212-1500
eclipseProduct      org.eclipse.epp.package.cpp.product
javaRuntimeVersion  1.8.0_101-b13
osgiWs              win32
osgiOs              Windows10
osgiOsVersion       10.0.0
osgiArch            x86_64
severity            UNKNOWN

-------
BUNDLES
-------
name                org.eclipse.core.databinding.observable
version             1.5.0.v20150422-0725

name                org.eclipse.core.databinding
version             1.5.0.v20150422-0725

name                org.eclipse.core.runtime
version             3.11.1.v20150903-1804

name                org.eclipse.e4.core.contexts
version             1.4.0.v20150828-0818

name                org.eclipse.e4.core.di
version             1.5.0.v20150421-2214

name                org.eclipse.e4.ui.workbench
version             1.3.1.v20160203-0951

name                org.eclipse.e4.ui.workbench.swt
version             0.13.0.v20150504-0621

name                org.eclipse.emf.common
version             2.11.1.v20160208-0816

name                org.eclipse.emf.ecore
version             2.11.2.v20160208-0816

name                org.eclipse.epp.logging.aeri.core
version             1.100.0.v20160211-1103

name                org.eclipse.epp.logging.aeri.ide
version             1.100.0.v20160217-0435

name                org.eclipse.equinox.app
version             1.3.300.v20150423-1356

name                org.eclipse.equinox.launcher
version             1.3.100.v20150511-1540

name                org.eclipse.jface
version             3.11.1.v20160128-1644

name                org.eclipse.swt
version             3.104.2.v20160212-1350

name                org.eclipse.ui
version             3.107.0.v20150507-1945

name                org.eclipse.ui.forms
version             3.6.200.v20150506-2029

name                org.eclipse.ui.ide.application
version             1.1.0.v20150422-0725

name                org.eclipse.ui.ide
version             3.11.0.v20150825-2158







The following report will be sent to Eclipse:

------
STATUS
------
pluginId            org.eclipse.epp.logging.aeri.ide
pluginVersion       1.100.0.v20160217-0435
code                6
severity            4
message             Saving preferences failed: reporterEmail=null ; version: 1.100.0.v20160217-0435
fingerprint         84626ff933247513c93966a7f1067a50

Exception:java.lang.NullPointerException: null
	 at org.eclipse.core.internal.preferences.EclipsePreferences.put(EclipsePreferences.java:908)
	 at org.eclipse.ui.preferences.ScopedPreferenceStore.putValue(ScopedPreferenceStore.java:486)
	 at org.eclipse.epp.internal.logging.aeri.ide.di.SystemSettingsCreationFunction$1.notifyChanged(SystemSettingsCreationFunction.java:97)
	 at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
	 at org.eclipse.epp.logging.aeri.core.impl.UserSettingsImpl.setReporterEmail(UserSettingsImpl.java:217)
	 at org.eclipse.epp.logging.aeri.core.impl.UserSettingsImpl.eSet(UserSettingsImpl.java:299)
	 at org.eclipse.epp.logging.aeri.core.impl.SystemSettingsImpl.eSet(SystemSettingsImpl.java:356)
	 at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eSet(BasicEObjectImpl.java:1071)
	 at org.eclipse.epp.internal.logging.aeri.ide.utils.Servers.copyIfUnset(Servers.java:152)
	 at org.eclipse.epp.internal.logging.aeri.ide.utils.Servers.setAsDefaults(Servers.java:124)
	 at org.eclipse.epp.internal.logging.aeri.ide.dialogs.EclipseServerPage.dispose(EclipseServerPage.java:195)
	 at org.eclipse.jface.wizard.Wizard.dispose(Wizard.java:197)
	 at org.eclipse.jface.wizard.WizardDialog.hardClose(WizardDialog.java:846)
	 at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:807)
	 at org.eclipse.epp.internal.logging.aeri.ide.handlers.OpenSystemSetupWizardHandler$1.finishPressed(OpenSystemSetupWizardHandler.java:65)
	 at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:429)
	 at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	 at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.jface.window.Window.runEventLoop(Window.java:827)
	 at org.eclipse.jface.window.Window.open(Window.java:803)
	 at org.eclipse.epp.internal.logging.aeri.ide.handlers.OpenSystemSetupWizardHandler.execute(OpenSystemSetupWizardHandler.java:69)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
	 at java.lang.reflect.Method.invoke(null:-1)
	 at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:56)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:252)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:234)
	 at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	 at org.eclipse.epp.logging.aeri.core.SystemControl.executeHandler(SystemControl.java:109)
	 at org.eclipse.epp.internal.logging.aeri.ide.notifications.SetupSystemNotification$1.execute(SetupSystemNotification.java:44)
	 at org.eclipse.epp.internal.logging.aeri.ide.notifications.NotificationPopup$1.linkActivated(NotificationPopup.java:264)
	 at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleActivate(AbstractHyperlink.java:233)
	 at org.eclipse.ui.forms.widgets.ImageHyperlink.handleActivate(ImageHyperlink.java:201)
	 at org.eclipse.ui.forms.widgets.AbstractHyperlink.handleMouseUp(AbstractHyperlink.java:327)
	 at org.eclipse.ui.forms.widgets.AbstractHyperlink.access$2(AbstractHyperlink.java:311)
	 at org.eclipse.ui.forms.widgets.AbstractHyperlink$4.handleEvent(AbstractHyperlink.java:125)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(null:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(null:-1)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(null:-1)
	 at java.lang.reflect.Method.invoke(null:-1)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

------
REPORT
------
anonymousId         cf97e692-be11-40b0-ba43-640129c8f684
name                
email               
comment             
eclipseBuildId      4.5.2.M20160212-1500
eclipseProduct      org.eclipse.epp.package.cpp.product
javaRuntimeVersion  1.8.0_101-b13
osgiWs              win32
osgiOs              Windows10
osgiOsVersion       10.0.0
osgiArch            x86_64
severity            UNKNOWN

-------
BUNDLES
-------
name                org.eclipse.core.databinding.observable
version             1.5.0.v20150422-0725

name                org.eclipse.core.databinding
version             1.5.0.v20150422-0725

name                org.eclipse.core.runtime
version             3.11.1.v20150903-1804

name                org.eclipse.e4.core.contexts
version             1.4.0.v20150828-0818

name                org.eclipse.e4.core.di
version             1.5.0.v20150421-2214

name                org.eclipse.e4.ui.workbench
version             1.3.1.v20160203-0951

name                org.eclipse.e4.ui.workbench.swt
version             0.13.0.v20150504-0621

name                org.eclipse.emf.common
version             2.11.1.v20160208-0816

name                org.eclipse.emf.ecore
version             2.11.2.v20160208-0816

name                org.eclipse.epp.logging.aeri.core
version             1.100.0.v20160211-1103

name                org.eclipse.epp.logging.aeri.ide
version             1.100.0.v20160217-0435

name                org.eclipse.equinox.app
version             1.3.300.v20150423-1356

name                org.eclipse.equinox.launcher
version             1.3.100.v20150511-1540

name                org.eclipse.jface
version             3.11.1.v20160128-1644

name                org.eclipse.swt
version             3.104.2.v20160212-1350

name                org.eclipse.ui
version             3.107.0.v20150507-1945

name                org.eclipse.ui.forms
version             3.6.200.v20150506-2029

name                org.eclipse.ui.ide.application
version             1.1.0.v20150422-0725

name                org.eclipse.ui.ide
version             3.11.0.v20150825-2158

**Comment by St3dPrinter** [comment]
Just a question: did you use the AC6 IDE installer version or did you added AC6 plugin in an existing version of Eclipse?

**Comment by huixiesui** [comment]
Downloaded from the http://www.openstm32.org/ version “install_sw4stm32_win_64bits-v1.8.exe ”

“install_sw4stm32_win_64bits-latest”

**Comment by St3dPrinter** [comment]
Ok, thank you.
I will test it again.

**Comment by huixiesui** [comment]
After the existing Eclipse version add plug-ins can be compiled.
Thanks a lot.

**Comment by St3dPrinter** [comment]
Hi,

Yesterday evening, I've tested again the complete setup on Windows 10.
I used this installer:  install_sw4stm32_win_64bits_v1.8

Once installed:
- Set the workspace to stm32_cube
- Import  ->  General  ->  Existing Projects into workspace

Right click on the project name -> Refresh
Right click on the project name -> Build Project

And the compilation proceeded with success.
A colleague made the same procedure with success also.

Can you retry in your side with a complete re-installation of the Open STM32 tools? May be a problem occurred during the installation on your computer. And let me know what is the final status.

Thank you
Best Regards

**Comment by St3dPrinter** [comment]
Oups, I just see your answer.
The page was not correctly refreshed.

I'm happy to see that you have succeed.

**Comment by shangaoren** [comment]
What is the configuration that was used to make it work ?
 i'm getting mad trying to get the project compiled
